// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaNyS9QXduxd2nYvlVpVfiz-w6hSyB0tQ',
    appId: '1:559591399364:android:aed6eb84c8d4b835748e91',
    messagingSenderId: '559591399364',
    projectId: 'lets-chat-f05a6',
    storageBucket: 'lets-chat-f05a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQRw1lLxQL80NH1dWFuFOhM-5DXHFX3hU',
    appId: '1:559591399364:ios:97eb50a4f0ab3f8d748e91',
    messagingSenderId: '559591399364',
    projectId: 'lets-chat-f05a6',
    storageBucket: 'lets-chat-f05a6.appspot.com',
    androidClientId: '559591399364-l70uhak2ogtmrd6lldmgd4kf8c72382a.apps.googleusercontent.com',
    iosClientId: '559591399364-0orhb9l3unv06ab40p4gjvu19a3866kk.apps.googleusercontent.com',
    iosBundleId: 'com.fastgrowmore.letsChat',
  );
}
